# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'NutriFence (iOS)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'NVActivityIndicatorView'
  pod 'ALCameraViewController'
  pod 'CameraManager', '~> 3.0'

  # Pods for NutriFence (iOS)

  target 'NutriFence (iOS)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NutriFence (iOS)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
